# Generated by Django 5.0.7 on 2026-06-11 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('family_members', models.IntegerField()),
                ('emi_rent', models.DecimalField(decimal_places=2, max_digits=12)),
                ('annual_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('qualification', models.CharField(choices=[('Graduate', 'Graduate'), ('Post Graduate', 'Post Graduate'), ('Professional', 'Professional')], max_length=20)),
                ('earning_members', models.IntegerField()),
                ('predicted_spending', models.DecimalField(decimal_places=2, max_digits=12)),
                ('predicted_savings', models.DecimalField(decimal_places=2, max_digits=12)),
                ('savings_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
